const a = 10;
const b = 3;
const add = (a + b);
const sub = (a - b);
const mul = (a * b);
const div = (a / b);
const mod = (a % b);
const eq = (a == b);
const neq = (a != b);
const lt = (a < b);
const gt = (a > b);
const lte = (a <= b);
const gte = (a >= b);
const t = true;
const f = false;
const and = (t && f);
const or = (t || f);
const not = (!t);
process.exit(mul);
