- id: cargo-test
  name: Cargo Test
  entry: cargo test
  language: system
  pass_filenames: false
  stages: [pre-commit]

- id: pmd-cpd
  name: PMD CPD
  entry: pmd cpd src --language rust --minimum-tokens 35 --ignore-literals --ignore-identifiers
  language: system
  pass_filenames: false
  stages: [pre-commit]

- id: cargo-clippy
  name: Cargo Clippy
  entry: cargo clippy
  language: system
  pass_filenames: false
  stages: [pre-commit]

- id: cargo-fmt
  name: Cargo Format
  entry: cargo fmt
  language: system
  pass_filenames: false
  stages: [pre-commit]
