repos:
  - repo: local
    hooks:
      - id: cargo-test
        name: cargo test
        entry: cargo test
        language: system
        pass_filenames: false
        stages: [pre-commit]
      - id: cargo-clippy
        name: cargo clippy
        entry: cargo clippy --all-targets --all-features -- -D warnings
        language: system
        pass_filenames: false
        stages: [pre-commit]
      - id: pmd-cpd
        name: pmd cpd
        entry: pmd cpd --dir src --language rust --minimum-tokens 50
        language: system
        pass_filenames: false
        stages: [pre-commit]
