#!/bin/bash
export PATH="/usr/lib/jvm/java-21-openjdk-amd64/bin:$PATH"
bun test --coverage && bun run lint:fix && bun run format && bun run check:circular && bun run check:structure && JAVA_HOME=/usr/lib/jvm/java-21-openjdk-amd64 PATH="/usr/lib/jvm/java-21-openjdk-amd64/bin:$PATH" ./tools/pmd-bin-7.20.0/bin/pmd cpd --dir src tests --language typescript --minimum-tokens 50 && npm run visualize