#!/bin/bash
export PATH="/usr/lib/jvm/java-21-openjdk-amd64/bin:$PATH"
bun test\
	&& npm run cpd\
	&& bun run format\
	&& bun run lint:fix\
	&& bun run check:circular\
	&& bun run check:structure\
	&& bun run check:subdir-deps\
	&& npm run visualize